[pyprland]
plugins = [
  "scratchpads",
]

[scratchpads.term]
animation = "fromBottom"
command = "kitty"
class = "kitty"
lazy = fale
size = "45% 25%"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
lazy = true
size = "45% 75%"

[scratchpads.music]
animation = "fromTop"
command = "kitty --class flatpak run app.ytmdesktop.ytmdesktop"
class = "music"
size = "75% 60%"
